/* Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef LIBC12N_CORE_H
#define LIBC12N_CORE_H

/* Generated with cbindgen:0.27.0 */

/* Generated from c12n-core's extern "C" surface. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Create a new pipeline. Returns opaque pointer.
 *
 * `config_json`: JSON string with `max_concurrency` and `timeout_ms`.
 * Returns null on error.
 */
void *c12n_pipeline_new(const char *config_json);

/**
 * Evaluate a context through the pipeline.
 *
 * `pipeline`: pointer from `c12n_pipeline_new`.
 * `context_json`: JSON string matching `ClassificationContext`.
 *
 * Returns a heap-allocated JSON string. Caller must free with
 * `c12n_result_free`. Returns a JSON error object on failure.
 */
char *c12n_pipeline_evaluate(const void *pipeline, const char *context_json);

/**
 * Free a pipeline created by `c12n_pipeline_new`.
 */
void c12n_pipeline_free(void *pipeline);

/**
 * Free a result string returned by `c12n_pipeline_evaluate`.
 */
void c12n_result_free(char *result);

/**
 * Return the JSON string as-is (identity; included for API completeness).
 */
const char *c12n_result_json(const char *result);

#endif  /* LIBC12N_CORE_H */
