/**
 * Node-without-bundler entry point.
 *
 * Re-exports the full public API plus a `loadNodejs()` loader that picks
 * the `pkg/nodejs/` wasm-pack output instead of `pkg/bundler/`. Consumers
 * who import from `@hop-top/c12n/nodejs` get a `Pipeline.create()` that
 * resolves the nodejs target.
 *
 * The `--target nodejs` wasm-pack glue reads the `.wasm` synchronously
 * via `fs.readFileSync()` and exposes the same `Pipeline` class shape as
 * the bundler target, so the public surface is identical.
 */

import type { WasmModule } from './wasm-loader.js';
import { Pipeline, type PipelineConfig, type Logger } from './pipeline.js';

export * from './index.js';

/**
 * Load the nodejs-target wasm module via Node's CommonJS resolver.
 *
 * Unlike `loadBundler()`, this one resolves to `pkg/nodejs/` which is
 * generated by `wasm-pack build --target nodejs`. Node can `require()`
 * the `.js` glue file directly; no async `init()` step needed since the
 * nodejs target loads the `.wasm` synchronously at module load.
 */
export async function loadNodejs(): Promise<WasmModule> {
  const mod = (await import(/* @vite-ignore */ '../pkg/nodejs/c12n_core.js')) as WasmModule;
  return mod;
}

/**
 * Override of `Pipeline.create` that uses the nodejs loader. Same shape +
 * semantics as the bundler-target version.
 */
export async function createNodePipeline(
  opts: { config?: PipelineConfig; logger?: Logger } = {},
): Promise<Pipeline> {
  const wasm = await loadNodejs();
  if (typeof wasm.setPanicHook === 'function') {
    wasm.setPanicHook();
  }
  return new Pipeline({ wasm, config: opts.config, logger: opts.logger });
}
