/**
 * Node-without-bundler entry point.
 *
 * Re-exports the full public API, but overrides `Pipeline` with a
 * subclass whose static `create()` resolves the `pkg/nodejs/` wasm-pack
 * output instead of `pkg/bundler/`. Consumers who import from
 * `@hop-top/c12n/nodejs` therefore get a `Pipeline.create()` that works
 * under plain Node — the base-class `create()` would resolve
 * `pkg/bundler/` and throw `Cannot find module`.
 *
 * The `--target nodejs` wasm-pack glue reads the `.wasm` synchronously
 * via `fs.readFileSync()` and exposes the same `Pipeline` class shape as
 * the bundler target, so the public surface is identical. Instances are
 * `instanceof` the base `Pipeline` from `@hop-top/c12n`, so code that
 * accepts one accepts the other.
 */

import type { WasmModule } from './wasm-loader.js';
import { Pipeline as BasePipeline, type PipelineConfig, type Logger } from './pipeline.js';

// Re-export everything EXCEPT `Pipeline`, which is overridden below.
// A blanket `export * from './index.js'` would re-export the bundler
// `Pipeline` and shadow the nodejs one — that is the bug this file
// exists to avoid.
export type { PipelineConfig, PipelineOptions, Logger } from './pipeline.js';

export { normalizeContext, toWireContext } from './context.js';
export type { ClassificationContext, WireContext } from './context.js';

export { parseResult, PipelineResult } from './result.js';
export type { PipelineResultRaw, SignalResult, SignalType, ResultError } from './result.js';

export { loadBundler } from './wasm-loader.js';
export type { WasmModule, WasmPipelineCtor, WasmPipelineInstance } from './wasm-loader.js';

/**
 * Load the nodejs-target wasm module via Node's CommonJS resolver.
 *
 * Unlike `loadBundler()`, this one resolves to `pkg/nodejs/` which is
 * generated by `wasm-pack build --target nodejs`. Node can `require()`
 * the `.js` glue file directly; no async `init()` step needed since the
 * nodejs target loads the `.wasm` synchronously at module load.
 */
export async function loadNodejs(): Promise<WasmModule> {
  // The nodejs wasm-pack target's `default` export is the raw module
  // namespace object, not the bundler target's async init function —
  // narrower than what WasmModule declares, so this cast goes via
  // `unknown`. Only `Pipeline`/`setPanicHook` are used off the nodejs
  // path; `default()` is never called here.
  const mod = (await import(/* @vite-ignore */ '../pkg/nodejs/c12n_core.js')) as unknown as WasmModule;
  return mod;
}

/**
 * Classification pipeline, nodejs-target flavour.
 *
 * Identical to the base `Pipeline` in every respect except that
 * `create()` loads `pkg/nodejs/` rather than `pkg/bundler/`. Exported
 * under the name `Pipeline` from the `@hop-top/c12n/nodejs` subpath so
 * the documented quickstart works verbatim:
 *
 * ```ts
 * import { Pipeline } from '@hop-top/c12n/nodejs';
 * const pipeline = await Pipeline.create();
 * ```
 */
export class Pipeline extends BasePipeline {
  /**
   * Lazy-load the nodejs-target wasm module and construct a pipeline.
   *
   * Overrides `BasePipeline.create`, which resolves `pkg/bundler/` and
   * throws `Cannot find module` under plain Node.
   */
  static override async create(
    opts: { config?: PipelineConfig; logger?: Logger } = {},
  ): Promise<Pipeline> {
    const wasm = await loadNodejs();
    if (typeof wasm.setPanicHook === 'function') {
      wasm.setPanicHook();
    }
    return new Pipeline({ wasm, config: opts.config, logger: opts.logger });
  }
}

/**
 * Construct a nodejs-target pipeline.
 *
 * Retained as a named alternative to `Pipeline.create()` — both take the
 * same options and return the same type. Prefer `Pipeline.create()`; it
 * matches the bundler-subpath surface.
 */
export async function createNodePipeline(
  opts: { config?: PipelineConfig; logger?: Logger } = {},
): Promise<Pipeline> {
  return Pipeline.create(opts);
}
